language: python
python:
 - "2.7"
# Install dependencies
install:
 - pip install -r requirements.txt
env:
- DJANGO_VERSION=1.11.6
script:
 - python manage.py test
after_success:
 - python manage.py test --with-coverage --cover-package=quiz
notifications:
 slack:
  on_success: change
  on_failure: always
