language: python
python:
 - "2.7"
# Install dependencies
install:
 - pip install -r requirements.txt
env:
- DJANGO_VERSION=1.11.6
script:
 - py.test
after_success:
 - cd medicapp; python manage.py runserver
