# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20171218_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='age',
            new_name='dob',
        ),
    ]
